name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build-win
      run: go build -o ChatRat-Windows.exe -v ./...
      env:
        GOOS: windows
        GOARCH: amd64
      
    - name: Build-linux-x86
      run: go build -o ChatRat-Linux-x86 -v ./...
      env:
        GOOS: linux
        GOARCH: amd64
        
    - name: Build-linux-arm64
      run: go build -o ChatRat-Linux-arm64 -v ./...
      env:
        GOOS: linux
        GOARCH: arm64
    
    - name: Build-linux-arm
      run: go build -o ChatRat-Linux-arm -v ./...
      env:
        GOOS: linux
        GOARCH: arm
        
    - name: Test
      run: go test -v ./...
        
    - name: "Build & test"
      run: |
          echo "done!"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.txt
          ChatRat-Windows.exe
          ChatRat-Linux-x86
          ChatRat-Linux-arm64
          ChatRat-Linux-arm
          settings.json

